language: node_js
node_js:
- '4'
- '6'
sudo: false
branches:
  only:
  - master
  - develop
  - /^v?(\d\.){2}\d$/
notifications:
  email:
  - nfantone@gmail.com
before_install:
  - npm i -g npm
script: npm run validate
after_success:
  - test $TRAVIS_NODE_VERSION == '6' && bash <(curl -s https://codecov.io/bash)
deploy:
  provider: npm
  email: nfantone@gmail.com
  api_key:
    secure: PKTP7urawBqTihUIyVUqtAysnfaJRXTWaAtRyT+z5fdb19/SqyKKSyu3j6VuBPtn/GGYj3xulZ5qzMfiE2mwcM1UQcq6LVB4tSoXgEMZ3MGfSNQ3Jjca6eWLG6KJl1LOxhCe5y2kEJrcLTHpc9LE7g5J7JDP/s+egUVYaozcEwI=
  on:
    tags: true
    repo: senecajs/seneca-amqp-transport
    node_js: '6'
cache:
  bundler: true
  directories: node_modules
