language: node_js
node_js:
- '8'
- '10'
sudo: false
branches:
  only:
  - master
  - develop
  - /^v?(\d\.){2}\d$/
  - /^greenkeeper/.*$/
notifications:
  email:
  - nfantone@gmail.com
before_install:
  - npm i -g npm
  - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script: npm run integrate
after_script: greenkeeper-lockfile-upload
services:
  - rabbitmq
after_success:
  - test $TRAVIS_NODE_VERSION == '8' && bash <(curl -s https://codecov.io/bash)
deploy:
  provider: npm
  email: nfantone@gmail.com
  api_key:
    secure: PKTP7urawBqTihUIyVUqtAysnfaJRXTWaAtRyT+z5fdb19/SqyKKSyu3j6VuBPtn/GGYj3xulZ5qzMfiE2mwcM1UQcq6LVB4tSoXgEMZ3MGfSNQ3Jjca6eWLG6KJl1LOxhCe5y2kEJrcLTHpc9LE7g5J7JDP/s+egUVYaozcEwI=
  on:
    tags: true
    repo: senecajs/seneca-amqp-transport
    node_js: '8'
cache:
  directories: node_modules
